### PR TITLE
Fixed compile error

### PR DESCRIPTION
**Pull request by GDR**
Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

### CODE REVIEW

**Comment by bashoogzaad** [comment]
When is this pull request going to be merged? Got a compile error now when building the app with angular cli

**Comment by Hacklone** [comment]
Hey,

Thanks for contributing. 👍 
Which version of cli are you using? Because it's working for me and it should work without putting it into a function.

For example material design switched to non function module providing too:
https://material.angular.io/guide/getting-started

Barna

**Comment by bashoogzaad** [comment]
Hey,

I am using "@angular/cli": "^1.0.0-beta.32.3"

**Comment by bashoogzaad** [comment]
Any comments on this @Hacklone? I like my build to succeed ;) . See error log here: https://travis-ci.org/bashoogzaad/storm-webshop

**Comment by Hacklone** [comment]
Thanks for fixing this :)

**Comment by GDR** [comment]
:dancer:

**Pull request merged**
